# Site settings
name: Math and Pencil 
title: 
email: info@mathandpencil.com
description: "Bringing Your Ideas To Life"
baseurl: ""
url: "https://www.socialq.com"
username: "mathandpencil"

# Build settings
markdown: kramdown
permalinks: pretty
